AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  crypto-auto-buy

Globals:
  Function:
    Runtime: python3.9
    Handler: app.lambda_handler
    Timeout: 600
    MemorySize: 128
    Architectures:
        - x86_64
    Environment:
      Variables:
        SECRET_BUCKET: !Ref CryptoBuyS3Bucket # Name of automatically deployed S3 bucket containing secrets.
        KRAKEN_SECRET_KEY: "kraken_secrets.json" # File containing Kraken API key, you put this in (structure is defined in README)
        MONTHLY_FREQ: !Ref MonthlyFrequency
        MONTHLY_FUND: !Ref MonthlyFund
        RATIO_BTC: !Ref RatioBTC
        RATIO_ETH: !Ref RatioETH
        ETH_WITHDRAW_THRESH: !Ref ETHWithdrawThreshold
        BTC_WITHDRAW_THRESH: !Ref BTCWithdrawThreshold

Parameters:
  SNSEmailParameter:
    Type: String
    Description: Enter email address for execution failure SNS topic subscription.
  MonthlyFrequency:
    Type: Number
    Description: Number of times to buy in a month.
    Default: 2
  MonthlyFund:
    Type: Number
    Description: How much in £ to invest per month.
    Default: 300
  RatioBTC:
    Type: Number
    Description: Proportion of MONTHLY_FUND to invest in BTC.
    Default: 0.5
  RatioETH:
    Type: Number
    Description: Proportion of MONTHLY_FUND to invest in ETH.
    Default: 0.5
  ETHWithdrawThreshold:
    Type: Number
    Description: How much £ in ETH balance before withdrawing.
    Default: 600
  BTCWithdrawThreshold:
    Type: Number
    Description: How much £ in BTC balance before withdrawing.
    Default: 300

Resources:
  CryptoBuyS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  KrakenBuyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: kraken_buy
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref CryptoBuyS3Bucket
      Events:
        CryptoBuySchedule:
          Type: Schedule
          Properties:
            Schedule: cron(30 6 3,18 * ? *) # Twice a month, 3rd and 18th at 6:30am UTC - must be consistent with MONTHLY_FREQ global variable
            Description: Automatically buys cryptocurrencies based on schedule rules.
            Enabled: true
      EventInvokeConfig:
        MaximumRetryAttempts: 0

  CryptoBuyTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
      - Endpoint: !Ref SNSEmailParameter
        Protocol: email
  
  ExecutionFailureAlarm:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      ActionsEnabled: true
      AlarmDescription: 'Sends an alarm when the Kraken auto-buy script fails.'
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref KrakenBuyFunction
      EvaluationPeriods: 1
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 21600
      Threshold: 1
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref CryptoBuyTopic

Outputs:
  KrakenBuyFunction:
    Description: "Kraken Buy Function ARN"
    Value: !GetAtt KrakenBuyFunction.Arn
  CryptoBuyTopic:
    Description: "Crypto Buy SNS Topic ARN"
    Value: !Ref CryptoBuyTopic