AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  crypto-auto-buy

Resources:
  CryptoBuyStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachine/crypto_autobuy.asl.json
      DefinitionSubstitutions:
        CoinbaseBuyFunctionArn: !GetAtt CoinbaseBuyFunction.Arn
        KuCoinBuyFunctionArn: !GetAtt KuCoinBuyFunction.Arn
        KuCoinWaitFunctionArn: !GetAtt KuCoinWaitFunction.Arn
      Events:
        CryptoBuySchedule:
          Type: Schedule
          Properties:
            Description: Automatically buys cryptocurrencies based on schedule rules
            Enabled: true
            Schedule: cron(30 6 1,15 * ? *) # Twice a month, 1st and 15th at 6:30am UTC
            Input: '{"secret_bucket": "crypto-auto-buy", "cb_secret_key": "cbpro-api-secret.json", "kc_secret_key": "kucoin-api-secret.json", "MONTHLY_FREQ": 2, "MONTHLY_FUND": 400, "RATIO_BTC": 0.425, "RATIO_ETH": 0.425, "RATIO_OPCT": 0.1, "RATIO_TRAC": 0.9}'
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref CoinbaseBuyFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref KuCoinBuyFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref KuCoinWaitFunction

  UtilityLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: util_layer
      CompatibleRuntimes:
        - python3.9
    Metadata:
      BuildMethod: python3.9

  CoinbaseBuyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/coinbase_buy/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Layers:
      - !Ref UtilityLayer
      Policies:
        - S3ReadPolicy:
            BucketName: "crypto-auto-buy"

  KuCoinBuyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/kucoin_buy/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Layers:
      - !Ref UtilityLayer
      Policies:
        - S3ReadPolicy:
            BucketName: "crypto-auto-buy"

  KuCoinWaitFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/kucoin_wait/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Layers:
      - !Ref UtilityLayer
      Policies:
        - S3ReadPolicy:
            BucketName: "crypto-auto-buy"

Outputs:
  # CryptoBuyStateMachineHourlyTradingSchedule is an implicit Schedule event rule created out of Events key under Serverless::StateMachine
  CryptoBuyStateMachineArn:
    Description: "Crypto AutoBuy State machine ARN"
    Value: !Ref CryptoBuyStateMachine
  CryptoBuyStateMachineRoleArn:
    Description: "IAM Role created for Crypto AutoBuy State machine based on the specified SAM Policy Templates"
    Value: !GetAtt CryptoBuyStateMachineRole.Arn
